docker-up:
	docker-compose up -d

docker-down:
	docker-compose down

install-packages:
	pip install --upgrade pip
	pip install --editable .
	pip install -r requirements.txt
	
venv:
	python3 -m venv .env
